name: auxtel_aos

channels:
  - conda-forge

dependencies:
  - python>3.8
  - pip
  - numpy
  - matplotlib
  - scipy
  - jupyterlab
  - ipywidgets
  - galsim
  - cmake
  - pip:
      - batoid
      - danish
      - lsst-sphgeom
      - git+https://github.com/jmeyers314/wfsim.git
